# Generated by Django 3.1.3 on 2021-01-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='south',
            old_name='quality',
            new_name='quantity',
        ),
    ]
